import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  

  return (
    <>
    
    <div className={styles.container}>
      <Head>
        <title>WuWuMelon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p> */}

        <div className={styles.grid}>
        <div className="card">
        <div className="card-image">
          <Image 
           priority
           
           src="/images/instructor-background.jpeg"
           width="100%" 
           height="70%" 
           layout="responsive" 
         
           alt=""/>
          <span className="card-title">Fundamentals of yoga</span>
        </div>
        <div className="card-content">
          <p>Learn the fundamentals of yoga with a certified yoga instructor. This is Carol. She has been instructing yoga classes for 4 years
                with over 500 hours of experience.</p>
        </div>
        <div className="card-action">
          <a className="waves-effect waves-light btn #69f0ae green accent-2" href="https://byu.zoom.us/j/99886472539?pwd=azl1VnpFMlF5UWkxUld5T3l5NXVBZz09">View Class</a>
          
        </div>
      </div>
        </div>
      </main>
    </div>
    </>
  )
}
